name: hostapp
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  firebase_auth: ^2.0.0
  rxdart: ^0.26.0
  flutter_secure_storage: ^4.2.0
  google_sign_in: ^5.0.4
  popup_menu: ^1.0.5
  device_info: ^2.0.2
  apple_sign_in: ^0.1.0
  provider: ^5.0.0
  google_fonts: ^2.1.0 #Styling text fonts
  intro_slider: ^3.0.2  #Intro slider for onBoardScreen
  flutter_spinkit: ^5.0.0 #for loading
  flutter_icons: ^1.1.0
  firebase_analytics: ^8.2.0
  firebase_dynamic_links: ^2.0.7
  fluttertoast: ^8.0.7
  getflutter: ^1.1.3
  responsive_builder: ^0.4.1
  image_picker: ^0.8.2
  country_list_pick: ^1.0.1+5
  flutter_screenutil: ^5.0.0+2
  file_picker: ^3.0.3
  international_phone_input: ^1.0.4
  graphql_flutter: ^5.0.0
  sticky_headers: ^0.2.0
  pull_to_refresh: ^2.0.0
  shared_preferences: ^2.0.6
  intl: ^0.17.0
  share: ^2.0.4
  date_format: ^2.0.2
  string_validator: ^0.3.0
  country_code_picker: ^2.0.2 # for country code picker
  firebase_core: ^1.4.0
  firebase_auth_oauth: ^1.0.2
  firebase_remote_config: ^0.10.0+3
  url_launcher: ^6.0.9
  firebase_performance: ^0.7.0+7
  firebase_crashlytics: ^2.1.1
  grouped_list: ^4.0.0
  device_id: ^0.2.0
  firebase_messaging: ^10.0.4
  flutter_local_notifications: any
  android_intent: ^2.0.2
  get_it: any
  liquid_swipe: ^2.1.0
  flutter_datetime_picker:
    git:
      url: https://github.com/Realank/flutter_datetime_picker.git
      ref: master
  flutter_google_places: any
  stacked: ^2.2.2
  #provider_architecture: ^1.0.5
  # flutter_places_dialog: ^1.0.5
  #device_preview: ^0.7.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  test:
  flutter_launcher_icons: ^0.9.0

flutter_icons:
  image_path: "assets/images/grlogo.png"
  android: true
  ios: true
  adaptive_icon_background: "#ffffff"


flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/tester_images/
