name: hostapp
description: A new Flutter project.

version: 1.0.0+11

environment:
  sdk: ">=2.3.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  firebase_auth: ^0.15.3+1
  rxdart: 0.23.1
  flutter_secure_storage: ^3.3.1+1
  google_sign_in: ^4.1.1
  popup_menu: ^1.0.5
  device_info: ^0.4.2+4  
  apple_sign_in: ^0.1.0
  provider: ^4.0.3
  google_fonts: ^0.5.0+1 #Styling text fonts
  intro_slider: ^2.2.8 #Intro slider for onBoardScreen
  flutter_spinkit: 4.1.0 #for loading
  device_preview: ^0.2.6
  get_it: ^3.0.1
  flutter_icons: ^1.0.0+1
  firebase_analytics: ^5.0.11
  firebase_dynamic_links: ^0.5.0+11
  fluttertoast: ^4.0.1
  getflutter: ^1.0.2
  provider_architecture: ^1.0.5
  responsive_builder: ^0.1.4
  image_picker: ^0.6.3+1
  country_list_pick: ^1.0.0+1
  flutter_screenutil: ^1.0.2
  file_picker: ^1.4.3+2
  international_phone_input: ^1.0.2
  graphql_flutter: ^3.0.0
  sticky_headers: ^0.1.8+1
  pull_to_refresh: ^1.5.8
  shared_preferences: ^0.5.7+3
  # flutter_places_dialog: ^1.0.5

  intl: ^0.16.1
  flutter_google_places: ^0.2.4
  flutter_datetime_picker:
    git:
      url: https://github.com/derohimat/flutter_datetime_picker.git
  share: ^0.6.3+6
  date_format: ^1.0.8
  string_validator: ^0.1.3
  #flutter_signin_button: ^1.0.0 #for signin button
  country_code_picker: ^1.2.4 # for country code picker
  firebase_core: ^0.4.3+1
  firebase_auth_oauth: ^0.1.0
  firebase_remote_config: ^0.3.0+3
  url_launcher: ^5.4.2
  firebase_performance: ^0.3.1+7
  firebase_crashlytics: ^0.1.3+3
  font_awesome_flutter: ^8.8.1
  grouped_list: ^3.2.3
  firebase_auth_mocks:
  mockito: ^4.1.1
  device_id: ^0.2.0
  firebase_messaging: ^6.0.16
  flutter_local_notifications: ^1.4.4+2
  android_intent: ^0.3.7+3



dev_dependencies:
  flutter_test:
    sdk: flutter
  test:
  flutter_launcher_icons: ^0.7.5

flutter_icons:
  image_path: "assets/images/grlogo.png"
  android: true
  ios: true
  adaptive_icon_background: "#ffffff"
  

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/tester_images/
