name: hostapp
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.3.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  firebase_auth: ^0.15.3+1
  flutter_secure_storage: ^3.3.1+1
  google_sign_in: ^4.1.1
  firebase_dynamic_links: ^0.5.0+9
  cloud_firestore: ^0.13.0+1
  firebase_database: ^3.0.9 
  device_info: ^0.4.1+4  
  apple_sign_in: ^0.1.0
  shared_preferences: ^0.5.6+1
  provider: ^4.0.1
  google_fonts: ^0.2.0 #Styling text fonts
  intro_slider: ^2.2.8 #Intro slider for onBoardScreen
  flutter_spinkit: 4.1.0 #for loading
  device_preview: ^0.2.6
  get_it: ^3.0.1
  intercom_flutter: ^2.0.7
  flutter_icons: ^1.0.0+1
  firebase_messaging: ^6.0.9
  firebase_analytics: ^5.0.9
  fluttertoast: ^3.1.3
  bottom_navy_bar: ^5.3.2
  configurable_expansion_tile: ^1.0.0
  localstorage: ^3.0.1+4
  encrypt: ^4.0.0
  getflutter: ^1.0.2
  provider_architecture: ^1.0.5
  responsive_builder: ^0.1.4
  arcore_plugin: ^0.1.4
  country_code_picker: ^1.2.2
  icofont_flutter: ^1.3.0
  image_picker: ^0.6.3+1
  firebase_storage: ^3.1.1
  country_list_pick: ^1.0.0+1
  flutter_screenutil: ^1.0.2
  file_picker: ^1.4.3+2
  international_phone_input: ^1.0.2
  rxdart: 0.23.1
  graphql_flutter: ^3.0.0
  # flutter_places_dialog: ^1.0.5
  google_places_flutter: ^1.0.5
  intl: ^0.16.1
  flutter_google_places: ^0.2.4
  flutter_datetime_picker: ^1.3.4
  share: ^0.6.3+6
  find_dropdown: ^0.1.8
  firebase_remote_config: ^0.3.0+1
  date_format: ^1.0.8
  string_validator: ^0.1.3


dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/images/
    - assets/tester_images/
